[package]
name = "hashgraph-like-consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
tracing = "0.1.41"
uuid = { version = "1.18.1", features = ["v4"] }

tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "full"] }
thiserror = "2.0.17"
sha2 = "0.10.9"
alloy-signer = "1.1.2"
async-trait = "0.1.85"

[build-dependencies]
prost-build = "0.13.5"
